#!/usr/bin/python
# -*- coding: utf-8 -*-

import config
from syslog import *

s_pri = {
    str(LOG_EMERG):   "log_emerg",
    str(LOG_ALERT):   "log_alert",
    str(LOG_CRIT):    "log_crit",
    str(LOG_ERR):     "log_err",
    str(LOG_WARNING): "log_warning",
    str(LOG_NOTICE):  "log_notice",
    str(LOG_INFO):    "log_info",
    str(LOG_DEBUG):   "log_debug"
}
s_fac = {
    str(LOG_KERN):    "log_kern",
    str(LOG_USER):    "log_user",
    str(LOG_MAIL):    "log_mail",
    str(LOG_DAEMON):  "log_daemon",
    str(LOG_AUTH):    "log_auth",
    str(LOG_LPR):     "log_lpr",
    str(LOG_NEWS):    "log_news",
    str(LOG_UUCP):    "log_uucp",
    str(LOG_CRON):    "log_cron",
    str(LOG_SYSLOG):  "log_syslog",
    str(LOG_LOCAL0):  "log_local0",
    str(LOG_LOCAL1):  "log_local1",
    str(LOG_LOCAL2):  "log_local2",
    str(LOG_LOCAL3):  "log_local3",
    str(LOG_LOCAL4):  "log_local4",
    str(LOG_LOCAL5):  "log_local5",
    str(LOG_LOCAL6):  "log_local6",
    str(LOG_LOCAL7):  "log_local7"
}

with open('config.ini', 'w') as out:
    out.write("[BluRouter]\n")
    out.write("# Autogenerated. See config-example.ini for descriptions.\n\n")

    out.write("udp_ip         = "+config.UDP_IP                   +"\n")
    out.write("udp_subnet     = "+config.UDP_SUBNET               +"\n")
    out.write("udp_broadcast  = "+config.UDP_BROADCAST            +"\n")
    out.write("udp_port       = "+str(config.UDP_PORT)            +"\n\n")

    out.write("allow_ranges   = "+", ".join(config.ALLOW_RANGES)  +"\n")
    out.write("protected_nets = "+", ".join(config.PROTECTED_NETS)+"\n\n")

    out.write("syslog_pri     = "+s_pri[str(config.syslog_pri)]   +"\n")
    out.write("syslog_facil   = "+s_fac[str(config.syslog_facil)] +"\n\n")

    out.write("routefile      = "+str(config.routesfile)          +"\n")
    out.write("pidfile        = "+str(config.pidfile)             +"\n\n")

    out.write("endian         = "+str(config.endian)              +"\n\n")

    out.write("hello_interval = "+str(config.hello_interval)      +"\n")
    out.write("hello_timeout  = "+str(config.hello_timeout)       +"\n")
    out.write("select_timeout = "+str(config.select_timeout)      +"\n")
    out.write("max_ttl        = "+str(config.max_ttl)             +"\n")
    out.write("newip_sendnets = "+str(config.newip_sendnets)      +"\n")
